import math
angle = 60

print("==0==")
print(math.sin(math.radians(0)))
print(math.cos(math.radians(0)))
print(math.tan(math.radians(0)))
print("==90==")
print(math.sin(math.radians(90)))
print(math.cos(math.radians(90)))
print(math.tan(math.radians(90)))
print("==180==")
print(math.sin(math.radians(180)))
print(math.cos(math.radians(180)))
print(math.tan(math.radians(180)))
print("==270==")
print(math.sin(math.radians(270)))
print(math.cos(math.radians(270)))
print(math.tan(math.radians(270)))
print("==45==")
print(math.sin(math.radians(45)))
print(math.cos(math.radians(45)))
print(math.tan(math.radians(45)))
print("==custom==")
print(math.sin(math.radians(angle)))
print(math.cos(math.radians(angle)))
print(math.tan(math.radians(angle)))
